[workspace]
authors = ["fajaralfa <fajaralfrzi@gmail.com>"]
channels = ["conda-forge"]
name = "imphnen-hackathon"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.1,<3.15"
ruff = ">=0.14.8,<0.15"

[pypi-dependencies]
pytest = ">=9.0.1,<10"
google-genai = ">=1.53.0,<2"
fastapi = { version = ">=0.123.10, <0.124", extras = ["standard"] }
python-jose = { version = ">=3.5.0, <4", extras = ["cryptography"] }
pillow = ">=12.0.0, <13"
pydantic-settings = ">=2.12.0, <3"
mypy = ">=1.19.0, <2"
types-python-jose = ">=3.5.0.20250531, <4"
