name: imphenhackaton
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.2
  google_fonts: ^6.3.0
  google_sign_in: ^6.2.1
  http: ^1.2.0
  image_picker: ^1.2.0
  intl: ^0.19.0
  share_plus: ^10.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/png/
    - .env