name: CI/CD

on:
  push:
    branches: [main]

jobs:
  ci:
    name: "CI - Run Tests"
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pixi
        run: curl -fsSL https://pixi.sh/install.sh | sh

      - name: Add Pixi to PATH
        run: echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: pixi install

      - name: Run tests
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: pixi run pytest

      - name: Debug VPS_HOST
        run: |
          echo "VPS_HOST length: ${#GITHUB_HOST}"
        env:
          GITHUB_HOST: ${{ secrets.VPS_HOST }}

  cd:
    name: "CD - Deploy to VPS"
    runs-on: ubuntu-latest
    needs: ci                  # deploy only runs if CI passes
    environment: Deployment
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /home/deploy/apps/captionize
            git fetch origin main
            git reset --hard origin/main
            /home/deploy/.pixi/bin/pixi install
            sudo systemctl restart captionize.service
