name: CI/CD

on:
  push:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # --- CI SECTION ---
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pixi
        run: curl -fsSL https://pixi.sh/install.sh | sh

      - name: Add Pixi to PATH
        run: echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: pixi install

      - name: Run tests
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: pixi run pytest

      # --- CD SECTION ---
      - name: Deploy to VPS via SSH
        if: success()
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }} # private key
          port: 22
          script: |
            cd ~/apps/imphnen-hackathon
            git pull origin main
            pixi install
            sudo systemctl restart fastapi-app.service